name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install wasmtime 
        if: steps.cacheWasmtime.outputs.cache-hit != 'true'
        run: 
          mkdir -p /home/runner/bin
          echo "/home/runner/bin" >> $GITHUB_PATH
          wget https://github.com/bytecodealliance/wasmtime/releases/download/v0.18.0/wasmtime-v0.18.0-x86_64-linux.tar.xz
          tar xf wasmtime-v0.18.0-x86_64-linux.tar.xz
          cp wasmtime-v0.18.0-x86_64-linux/wasmtime /home/runner/bin/wasmtime
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
